{
 "title": "Silo Node Dashboard",
 "description": "Silo Nodes Grafana Dashboard - https://silo.pgsty.com/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(minio_node_drive_total,server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Drives",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_node_drive_total{job=~\"$scrape_jobs\",server=\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_node_drive_online_total{job=~\"$scrape_jobs\",server=\"$server\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_node_drive_offline_total{job=~\"$scrape_jobs\",server=\"$server\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Drive Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_drive_total_bytes{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "Total [{{drive}}]"
    },
    {
     "expr": "minio_node_drive_used_bytes{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "Used [{{drive}}]"
    },
    {
     "expr": "minio_node_drive_free_bytes{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "Free [{{drive}}]"
    }
   ]
  },
  {
   "title": "Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_free_inodes{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "[{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Latency (micro sec)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_latency_us{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "[{{drive}}:{{api}}]"
    }
   ]
  },
  {
   "title": "Drive Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_errors_availability{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "[{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Timeout Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_errors_timeout{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "[{{drive}}]"
    }
   ]
  },
  {
   "title": "IO Operations Waiting",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_io_waiting{job=~\"$scrape_jobs\",server=\"$server\"}",
     "legendFormat": "[{{drive}}]"
    }
   ]
  }
 ]
}